### ISSUE TITLE
extract people from database and transform to RDF

### ISSUE THREAD

**Issue by lklic** [villaitatti/yashiro_project#5]
need extract the data from SQL database about the people, convert to RDF and add wikidata links. 

Linking them back to the letters should be done manually as annotations, as there are very few links

**Comment by gspinaci** [comment]
People extracted from in https://github.com/villaitatti/yashiro_project_utilities/commit/8a974af7f66bd31d645ce43e3bd6733e5b5df0b8.

Should we encode them as annotations? @lklic thoughts?
